FROM golang:1.9.2 as builder
RUN mkdir -p /user/src/app
WORKDIR /user/src/app
RUN go get -d -v github.com/gorilla/mux \
	&& go get -d -v go.mongodb.org/mongo-driver/bson \
	&& go get -d -v go.mongodb.org/mongo-driver/bson/primitive \
	&& go get -d -v go.mongodb.org/mongo-driver/mongo \
	&& go get -d -v go.mongodb.org/mongo-driver/mongo/options 
COPY . /user/src/app
CMD ["go","run","main.go"]
 
