version: '3'
services:
  go:
    build:
        context: . 
        dockerfile: dockerfile
    ports:
     - "9090:9090"
    links:
     - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    command: mongod
volumes:
   mongodata:

